version: '3'

services:
  db:
    image: 'postgres:14'
    container_name: 'cocktail-maker-db'
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cocktail-maker
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
